# Generated by Django 4.2.8 on 2023-12-24 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_team_files'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='files',
        ),
    ]
