# Generated by Django 2.1.5 on 2019-03-30 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190329_1434'),
        ('tasks', '0005_team_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='team',
            name='members',
        ),
        migrations.AddField(
            model_name='task',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Team'),
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
