# Generated by Django 4.2.8 on 2023-12-24 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_task_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to='comment_files/'),
        ),
    ]
