# Generated by Django 4.2.8 on 2023-12-24 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_comment_files'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='files',
            new_name='file',
        ),
    ]
